### PR TITLE
Remove evil retry

### PR DESCRIPTION
**Pull request by clupprich**
This PR will remove a `retry` in the SOAP client's `soap_request` method, which was causing weird issues on BULQ (like, triggered sends submitted multiple times, because we were running into a timeout and then we automagically started adding entries a second time).
Even though this PR will not be our final solution to that problem, I'd still would like it to be removed, cause I find it pretty _WTF?_

Also, I've fixed some specs that I broke when we were updating the token refresh - the remaining failing specs are not my fault, I swear! ;) Still looking into those, will open a separate PR (needs some digging).

### CODE REVIEW

**Comment by fritzgrabo** [comment]
This is all super-weird: The original code retries once, then just-reraises the caught error if it happens again => I see now why those triggered sends have been sent out twice (b/c of the single retry), but then again I'm surprised that the re-raised error didn't bubble up and got noticed in Blinq/Bulq? Does that mean that an error was thrown only one time, and the retry went through flawlessly? I don't even ...

In either case, I guess we'll soon see errors raised in this gem bubble up to Blinq/Bulq. I'm interested to see which errors these are.

**Comment by fritzgrabo** [comment]
PS: I say this is definitely better than the previous version: review passed.

**Comment by clupprich** [comment]
We guess we were seeing timeout issues on our end, at least that would explain why it didn't bubble up. That's also the reason why I'm not too concerned about an increase of exceptions from this gem - if we would so something really wrong, we would have already seen it, as it won't go away over time.

**Comment by jec006** [comment]
Yah, we definitely see a Timeout error in the resque cleaner when this happens, but it also sends the email twice (and even more times if we retry).

**Comment by jec006** [comment]
Merging this into gem, blinq and bulq will need to update their gem versions to include these changes before they're live anywhere.

**Pull request merged**
